language: cpp
dist: trusty

stages:
    - ccpp
    - python

env:
    global:
        - TWINE_USERNAME=Martinsos
        # Encrypted TWINE_PASSWORD:
        - secure: "VfgRi/hcUMLDYzATLS8JOuZo+wg0VNCmEojIJ3gpy89LAXgPN1Qx/2n3c52PPgFWgWFdDgns2SdxhQ1/810qb+65choy2fOgTULnyFcH3ZFTM5nINVHlGB5dLDUesKjrqqfIKHnwB6LAskHqHHPm/qv7WxUjQbcpR6mICsKB7h3NI7yUSc3tRPmd8tVBc/mTUXpMRVznTxGFCo/rC4f2y57GI9odjDxS4VqGS8T9Igvgyteg+ougXYbl84FIi3Bij6TQITa1rP9cFw/lfXMTM2m1czTonzAbgGPC6q7798MCGhLpEdxr+Zu9NPCS8aWFYdxMUYmsisjffDtTdIagZFh/14YrnQb2RxqnLTqSi20E+xXx16GcHhnMOxw/sSOh6HUEaXcbLNtx/mqMEa7mQEcIFBdXHWs/czTHz8xEoGnHIVHI5zqItoK3nUD0W/X6XUex8GP8obvjSKVw2k8X/0bZUaqSyNVbTfYcLmOk53Kx8vfXd82BbTOWiJVZmvuugqrshIEaLOyRhSaoC4Bj5KjfijM/gKPa+n8wVEQ/4hF4HpJKr/33cAm1URDGsDnfvHfxfeEwizTq8gCIxnbpOzSsd1M6+3MQLr48DE8uYM+wkG2F+KsCKe3OexLiaqHG7rVZh1R99nOykoqfjhxek3H1KGfx7qFbdK80AaVBiQo="



.ccpp: &ccpp
    stage: ccpp
    
    before_install:
      - eval "${MATRIX_EVAL}"
    
    install:
      - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install valgrind; fi
    
    before_script:
      # Build C/C++ library and apps.
      - mkdir -p build && cd build && CXXFLAGS="-Werror" cmake -GNinja .. && ninja -v && cd ..
    
    script:
      # Test C/C++ library using CTest.
      - ninja -C build -v test && cat build/Testing/Temporary/LastTest.log
      # Check for memory leaks. Returns 2 if there was a memory leak/error, otherwise returns runTests exit code,
      # which is 0 if all went fine or 1 if some of the tests failed. I test for memory leaks only on linux because
      # osx returns errors from system libraries, which I would have to supress.
      # This is run only on smaller number of tests, since executing on valgrind is slow.
      - if [ $TRAVIS_OS_NAME == "linux" ]; then valgrind --quiet --error-exitcode=2 --tool=memcheck --leak-check=full build/bin/runTests 2; fi

.python: &python
    stage: python

    install:
        - wget -qO- https://bootstrap.pypa.io/get-pip.py | python3
        - python3 -m pip install cibuildwheel==1.6.1

    script:
        # Build the wheels, put them into './wheelhouse'.
        # cibuildwheel needs to be run from python directory.
        # The python directory is mounted in the docker build containers,
        # so we need to copy the edlib source before running cibuild wheel.
        - cd bindings/python
        - make edlib # Copies edlib source to python dir.
        - |
            CIBW_SKIP="cp27-* pp* *-manylinux_i686" \
            CIBW_BEFORE_BUILD="make sdist" \
            CIBW_TEST_COMMAND="python3 {project}/test.py" \
            python3 -m cibuildwheel --output-dir wheelhouse
        - if [ $DEPLOY_SDIST_TO_PYPI ]; then make sdist; fi

    after_success:
        - |
            if [ $TRAVIS_TAG ]; then
                cd bindings/python
                python3 -m pip install twine
                python3 -m twine upload wheelhouse/*.whl
                if [ $DEPLOY_SDIST_TO_PYPI ]; then
                    python3 -m twine upload dist/edlib-*.tar.gz
                fi
            else
                echo "Skipping twine upload because not a tag, files built:"
                ls -l wheelhouse
                ls -l dist
            fi

jobs:
  include:
    # In order to catch as many weird edge cases in the code with -Werror as
    # possible, we want to test a large range of old and new compilers on both
    # Linux and macOS. This gives us the best possible coverage while maintaining
    # compatibility with a large number of compilers.
    - name: "C/CPP (Linux; GCC 4.9)"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - ninja-build
      env:
         - MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
      <<: *ccpp

    - name: "C/CPP (Linux; GCC 9)"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - ninja-build
      env:
        - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
      <<: *ccpp

    - name: "C/CPP (Linux; Clang 5.0)"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
      env:
        - MATRIX_EVAL="export CC=clang-5.0 && export CXX=clang++-5.0"
      <<: *ccpp

    - name: "C/CPP (OSX; XCode 11; Clang)"
      os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - ninja
      <<: *ccpp

    - name: "Python wheel (Linux)"
      language: python
      python:
          - "3.6"
      services: docker
      env:
        # We need to upload sdist only once, since it is same for all jobs,
        # so with this flag we specify which job will take care of that (this one).
        - DEPLOY_SDIST_TO_PYPI="true"
      <<: *python

    - name: "Python wheel (OSX)"
      os: osx
      language: shell
      <<: *python

    # TODO: Add windows x64 and linux aarch64 python wheel builds? Edlib users said they need them.
